blueprint:
  name: Camera Snapshot & Notification on Press # Added channel info to name
  description: Take snapshots and send notifications on motion detection, using the 'Doorbell' channel for Android.
  domain: automation
  input:
    camera_device:
      name: Camera
      description: The camera which creates the snapshot
      selector:
        entity:
          domain: camera    
    is_ios:
      name: Is it an iOS device?
      description: Toggle if your selected device runs iOS, default is Android
      selector:
        boolean:
      default: false
    notify_device:
      name: Device to notify
      description: Device needs to run the official Home Assistant app to receive notifications
      selector:
        device:
          integration: mobile_app
    motion_sensor:
      name: Motion sensor
      description: The sensor which triggers the snapshot creation
      selector:
        entity:
          domain: binary_sensor
    num_snapshots:
      name: Number of Snapshots
      description: Number of snapshots to take (between 1 and 5)
      selector:
        number:
          min: 1
          max: 5
          unit_of_measurement: snapshots
      default: 3      
    condition_auto:
      name: Add Condition(s) to run this Automation
      description: Add conditions if needed to run this automation at all. Note, if conditions return `false`, no actions will fire.
      default: []
      selector:
        condition: {}

trigger:
  platform: state
  entity_id: !input motion_sensor
  to: 'on'

variables:
  camera_device: !input camera_device
  camera_name: "{{ state_attr(camera_device, 'friendly_name') }}"
  camera_path: "{{ state_attr(camera_device, 'friendly_name') | lower | replace(' ', '_') }}"
  motion_sensor: !input motion_sensor
  motion_name: "{{ state_attr(motion_sensor, 'friendly_name') }}"
  is_ios: !input 'is_ios'
  num_snapshots: !input num_snapshots
  snapshot_access_file_path: '/local/snapshots/{{ camera_path }}_snapshot1.jpg' # Note: Only the first snapshot is sent
  condition_auto: !input condition_auto

action:
- if:
  - condition: !input condition_auto
  then:
  - repeat:
      count: "{{ num_snapshots }}"
      sequence:
        - service: camera.snapshot
          data:
            filename: "./www/snapshots/{{ camera_path }}_snapshot{{ repeat.index }}.jpg"
          target:
            entity_id: "{{ camera_device }}"
        - delay:
            milliseconds: 500
  - device_id: !input 'notify_device'
    domain: mobile_app
    type: notify
    title: "{{ motion_name }} Detected"
    message: "Motion detected by {{ motion_name }}."
    data: >
      {# --- MODIFICATION START --- #}
      {% set android_data = {"image": snapshot_access_file_path, "channel": "Doorbell", "importance": high} %}
      {# --- MODIFICATION END --- #}
      {% set ios_data = {"attachment": {"url": snapshot_access_file_path, "content_type": "JPEG", "push": {"interruption-level": "time-sensitive"}}} %}
      {{ ios_data if is_ios else android_data }}

mode: single
